spring:
  profiles:
    active: test
  mvc:
    static-path-pattern: /static/**
shiro:
  allowedUrl:
    - http://localhost:8080
    - http://localhost:8081
    - http://localhost:8082
    - http://go.mazhangjing.com:8090
    - http://go.mazhangjing.com
schedule:
  fixDurationMillSeconds: 10000
logging:
  level:
    root: info
    sql: debug
    web: info
    cm: debug
  path: taskLogs
  file:
    max-size: 10MB
  group:
    cm: com.mazhangjing
---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql:///spring?serverTimezone=Asia/Shanghai
    username: corkine
    password: mi960032
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  thymeleaf:
    cache: false
server:
  port: 8080
---
spring:
  profiles: real
  datasource:
    url: jdbc:mysql://cdb-aa6kk3oj.gz.tencentcdb.com:10015/sugerandsalt?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: corkine
    password: mi960032
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 60000
      max-lifetime: 300000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5Dialect

  thymeleaf:
    cache: false
server:
  port: 8099

  ##test-while-idle: true
  #    validation-query: SELECT 1
  #    time-between-eviction-runs-millis: 120000
  #    hikari:
  #      connection-test-query: SELECT 1
